### ISSUE TITLE
it is showing some problem while running PPerf

### ISSUE THREAD

**Issue by COOLshivam** [ili101/PPerf#3]
![image](https://cloud.githubusercontent.com/assets/13058236/24989919/b53637ce-202d-11e7-896a-39ef0bbe72af.png)

i tried to run PPerf.ps1 from windows PowerShell, but some exception is showing,

Please help

**Comment by krzydoug** [comment]
I'm aware this is an old thread. Just in case anyone else happens to encounter this. 

The ::new() method requires powershell version 5 or higher. You're probably on version 4.0

**Comment by ili101** [comment]
PowerShell version 5 or higher is officially supported, PS Requires comment fixed https://github.com/ili101/PPerf/pull/4
